import {
  Merchant,
  Courier,
  Delivery,
  CreditRecharge,
  Withdrawal,
  AuditLog,
  CentralSettings,
  OperatingZone,
  Praca
} from './types';

export const INITIAL_PRACAS: Praca[] = [
  {
    id: 'praca-centro',
    nome: 'Praça Central (Barão do Rio Branco)',
    endereco_referencia: 'Praça Central, Centro, Alagoinha-PB',
    latitude: -6.9535,
    longitude: -35.5463,
    ativa: true,
    mototaxistas_vinculados: 4,
    mototaxistas_disponiveis: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 'praca-mercado',
    nome: 'Praça do Mercado Público',
    endereco_referencia: 'Rua do Comércio / Mercado Público',
    latitude: -6.9542,
    longitude: -35.5451,
    ativa: true,
    mototaxistas_vinculados: 3,
    mototaxistas_disponiveis: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 'praca-patio-eventos',
    nome: 'Praça do Pátio de Eventos',
    endereco_referencia: 'Avenida Principal / Saída para Cuitegi',
    latitude: -6.9515,
    longitude: -35.542,
    ativa: true,
    mototaxistas_vinculados: 2,
    mototaxistas_disponiveis: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 'praca-hospital',
    nome: 'Praça da Saúde / Unidade Mista',
    endereco_referencia: 'Próximo à Unidade de Saúde Central',
    latitude: -6.955,
    longitude: -35.548,
    ativa: true,
    mototaxistas_vinculados: 1,
    mototaxistas_disponiveis: 0,
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_OPERATING_ZONES: OperatingZone[] = [
  {
    id: 'praca-centro',
    name: 'Praça Central (Barão do Rio Branco)',
    shortName: 'Praça Centro',
    bubbleArea: 'Centro da cidade, Matriz, Praça Central, Mercado',
    badgeColor: 'border-cyan-500/40 bg-cyan-500/15 text-cyan-300',
    icon: '🏙️',
    standardFee: 4.00,
    description: 'Ponto tradicional da Matriz no Centro de Alagoinha.',
  },
  {
    id: 'praca-mercado',
    name: 'Praça do Mercado Público',
    shortName: 'Mercado Público',
    bubbleArea: 'Mercado Municipal, bancos, comércio central',
    badgeColor: 'border-blue-500/40 bg-blue-500/15 text-blue-300',
    icon: '🛒',
    standardFee: 4.00,
    description: 'Atendimento rápido ao comércio e feira livre.',
  },
  {
    id: 'praca-patio-eventos',
    name: 'Praça do Pátio de Eventos',
    shortName: 'Pátio de Eventos',
    bubbleArea: 'Loteamentos, Pátio de Eventos, saída Cuitegi',
    badgeColor: 'border-emerald-500/40 bg-emerald-500/15 text-emerald-300',
    icon: '🎪',
    standardFee: 5.00,
    description: 'Região de expansão e eventos.',
  },
];

export const INITIAL_SETTINGS: CentralSettings = {
  nome_central: 'Central Nexo Viagens',
  cidade: 'Alagoinha - PB',
  taxa_passageiro_tipo: 'fixo',
  taxa_passageiro_valor: 0.00, // Configurável pelo Admin
  taxa_mototaxista_tipo: 'percentual',
  taxa_mototaxista_valor: 15.00, // 15% para a Central
  tarifa_base_corrida: 4.00,
  tarifa_km_adicional: 1.50,
  meta_saque_mototaxista: 250.00,
  nota_minima_qualidade: 3.8, // Trava automática de qualidade
  raio_busca_km: 5.0,
  tempo_limite_aceite_segundos: 45,
  // Sugestão 7: Tarifa Dinâmica por Eventos e Chuva (Clima Local)
  tarifa_dinamica_ativa: false,
  tarifa_dinamica_motivo: 'Chuva Intensa',
  tarifa_dinamica_adicional: 2.00,
  // Sugestão 8: Anti-Vaga Ocupada / Inatividade na Praça
  limite_inatividade_fila_minutos: 30,
  chave_pix_central: 'financeiro@nexoviagens.com.br',
  tipo_chave_pix_central: 'email',
  beneficiario_pix_central: 'Central Nexo Viagens • Alagoinha-PB',
  telefone_central: '(83) 99876-5432',
  
  // Compatibilidade
  centralName: 'Central Nexo Viagens',
  city: 'Alagoinha - PB',
  centralPixKey: 'financeiro@nexoviagens.com.br',
  centralPixKeyType: 'email',
  centralPixBeneficiary: 'Central Nexo Viagens • Alagoinha-PB',
  centralPhone: '(83) 99876-5432',
  centralCommissionRate: 0.15,
  goalAmount: 250.00,
  baseDeliveryFee: 4.00,
  minDeliveryFee: 4.00,
  maxDeliveryFee: 25.00,
  feeUrbanCentral: 4.00,
  feeUrbanDistante: 5.00,
  feePraca1Centro: 4.00,
  feePraca2PatioFestas: 5.00,
  operatingZones: DEFAULT_OPERATING_ZONES,
  adminUsername: 'admin',
  adminPassword: 'admin',
};

// Passageiros iniciais
export const INITIAL_MERCHANTS: Merchant[] = [
  {
    id: 'pass-01',
    name: 'Maria Clara da Silva',
    ownerName: 'Maria Clara da Silva',
    phone: '(83) 98822-1133',
    email: 'mariaclara@gmail.com',
    address: 'Rua Barão do Rio Branco, 45, Centro',
    creditBalance: 35.00,
    totalSpent: 48.00,
    totalDeliveries: 12,
    active: true,
    loginUsername: 'mariaclara',
    password: '123',
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    saldo_creditos: 35.00,
    total_gasto: 48.00,
    total_corridas: 12,
    ativo: true,
  },
  {
    id: 'pass-02',
    name: 'João Pedro Santos',
    ownerName: 'João Pedro Santos',
    phone: '(83) 99144-8877',
    email: 'joaopedro@gmail.com',
    address: 'Rua Nova, 120, Alagoinha-PB',
    creditBalance: 20.00,
    totalSpent: 32.00,
    totalDeliveries: 8,
    active: true,
    loginUsername: 'joaopedro',
    password: '123',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    saldo_creditos: 20.00,
    total_gasto: 32.00,
    total_corridas: 8,
    ativo: true,
  },
];

// Mototaxistas iniciais (com status de aprovação e praça)
export const INITIAL_COURIERS: Courier[] = [
  {
    id: 'moto-01',
    perfil_id: 'moto-01',
    name: 'Severino Silva (Biu da Moto)',
    phone: '(83) 98765-4321',
    cpf: '123.456.789-00',
    vehicleType: 'moto',
    vehiclePlate: 'QFA-4021',
    placa_veiculo: 'QFA-4021',
    modelo_veiculo: 'Honda CG 160 Fan Vermelha',
    cor_veiculo: 'Vermelha',
    cnh_numero: '0498234821',
    pixKey: '83987654321',
    pixKeyType: 'telefone',
    photoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    active: true,
    isOnline: true,
    disponibilidade: 'disponivel',
    status_aprovacao: 'aprovado',
    approvalStatus: 'aprovado',
    isApproved: true,
    authorizedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    authorizedBy: 'Central Nexo',
    praca_atual_id: 'praca-centro',
    praca_atual_nome: 'Praça Central (Barão do Rio Branco)',
    praca_entrou_em: new Date(Date.now() - 3600000 * 2).toISOString(), // Entrou há 2 horas (1º da fila)
    assignedZoneId: 'praca-centro',
    accumulatedBalance: 142.50,
    saldo_acumulado: 142.50,
    totalGrossEarned: 680.00,
    total_ganhos_brutos: 680.00,
    total_taxas_central: 102.00,
    totalNetPaid: 480.00,
    total_saques_pagos: 480.00,
    completedDeliveries: 125,
    total_corridas: 125,
    totalWithdrawalsCount: 2,
    avaliacao_media: 4.95,
    total_avaliacoes: 84,
    loginUsername: 'biu',
    password: '123',
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'moto-02',
    perfil_id: 'moto-02',
    name: 'José Carlos (Dedé Mototáxi)',
    phone: '(83) 99654-1122',
    cpf: '321.654.987-11',
    vehicleType: 'moto',
    vehiclePlate: 'MNZ-8912',
    placa_veiculo: 'MNZ-8912',
    modelo_veiculo: 'Yamaha Factor 150 Preta',
    cor_veiculo: 'Preta',
    cnh_numero: '0512839482',
    pixKey: 'dede@gmail.com',
    pixKeyType: 'email',
    photoUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    active: true,
    isOnline: true,
    disponibilidade: 'disponivel',
    status_aprovacao: 'aprovado',
    approvalStatus: 'aprovado',
    isApproved: true,
    authorizedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    authorizedBy: 'Central Nexo',
    praca_atual_id: 'praca-mercado',
    praca_atual_nome: 'Praça do Mercado Público',
    praca_entrou_em: new Date(Date.now() - 3600000 * 1).toISOString(), // 1º da fila na Praça do Mercado
    assignedZoneId: 'praca-mercado',
    accumulatedBalance: 88.00,
    saldo_acumulado: 88.00,
    totalGrossEarned: 350.00,
    total_ganhos_brutos: 350.00,
    total_taxas_central: 52.50,
    totalNetPaid: 200.00,
    total_saques_pagos: 200.00,
    completedDeliveries: 64,
    total_corridas: 64,
    totalWithdrawalsCount: 1,
    avaliacao_media: 4.88,
    total_avaliacoes: 42,
    loginUsername: 'dede',
    password: '123',
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    id: 'moto-03',
    perfil_id: 'moto-03',
    name: 'Lucas Ferreira (Candidato Novo)',
    phone: '(83) 98111-2233',
    cpf: '456.789.123-22',
    vehicleType: 'moto',
    vehiclePlate: 'QGB-5566',
    placa_veiculo: 'QGB-5566',
    modelo_veiculo: 'Honda Bros 160 Branca',
    cor_veiculo: 'Branca',
    cnh_numero: '0987654321',
    pixKey: '83981112233',
    pixKeyType: 'telefone',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    active: true,
    isOnline: false,
    disponibilidade: 'offline',
    status_aprovacao: 'pendente', // Sujeito à aprovação da Central
    approvalStatus: 'pendente',
    isApproved: false,
    praca_atual_id: 'praca-patio-eventos',
    praca_atual_nome: 'Praça do Pátio de Eventos',
    assignedZoneId: 'praca-patio-eventos',
    accumulatedBalance: 0,
    saldo_acumulado: 0,
    totalGrossEarned: 0,
    total_ganhos_brutos: 0,
    total_taxas_central: 0,
    totalNetPaid: 0,
    total_saques_pagos: 0,
    completedDeliveries: 0,
    total_corridas: 0,
    totalWithdrawalsCount: 0,
    avaliacao_media: 5.0,
    total_avaliacoes: 0,
    loginUsername: 'lucas',
    password: '123',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_DELIVERIES: Delivery[] = [
  {
    id: 'corr-001',
    code: '#00101',
    codigo: 101,
    passageiro_id: 'pass-01',
    passageiro_nome: 'Maria Clara da Silva',
    passageiro_telefone: '(83) 98822-1133',
    merchantId: 'pass-01',
    merchantName: 'Maria Clara da Silva',
    merchantPhone: '(83) 98822-1133',
    
    mototaxista_id: 'moto-01',
    mototaxista_nome: 'Severino Silva (Biu da Moto)',
    mototaxista_telefone: '(83) 98765-4321',
    mototaxista_placa: 'QFA-4021',
    mototaxista_modelo: 'Honda CG 160 Vermelha',
    courierId: 'moto-01',
    courierName: 'Severino Silva (Biu da Moto)',
    courierPhone: '(83) 98765-4321',
    
    praca_origem_id: 'praca-centro',
    praca_origem_nome: 'Praça Central (Barão do Rio Branco)',
    pracaZoneId: 'praca-centro',
    pracaZoneName: 'Praça Central (Barão do Rio Branco)',
    
    origem_endereco: 'Praça Central, Centro',
    pickupAddress: 'Praça Central, Centro',
    destino_endereco: 'Rua Nova, 180',
    deliveryAddress: 'Rua Nova, 180',
    
    valor_corrida: 4.00,
    deliveryFee: 4.00,
    taxa_passageiro: 0.00,
    taxa_mototaxista: 0.60, // 15%
    valor_destinado_central: 0.60,
    valor_liquido_mototaxista: 3.40,
    courierEarnings: 3.40,
    centralFee: 0.60,
    
    status: 'corrida_concluida',
    horario_solicitacao: new Date(Date.now() - 3600000 * 3).toISOString(),
    horario_aceitacao: new Date(Date.now() - 3600000 * 3 + 60000).toISOString(),
    horario_inicio: new Date(Date.now() - 3600000 * 3 + 300000).toISOString(),
    horario_conclusao: new Date(Date.now() - 3600000 * 3 + 900000).toISOString(),
    
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 3 + 900000).toISOString(),
    
    avaliacao_estrelas: 5,
    avaliacao_comentario: 'Muito rápido e atencioso. Moto novinha.',
    avaliado_em: new Date(Date.now() - 3600000 * 2).toISOString(),
    
    statusHistory: [
      { status: 'solicitada', timestamp: new Date(Date.now() - 3600000 * 3).toISOString(), note: 'Passageiro solicitou mototaxista' },
      { status: 'aceita', timestamp: new Date(Date.now() - 3600000 * 3 + 60000).toISOString(), note: 'Biu da Moto aceitou a corrida' },
      { status: 'corrida_iniciada', timestamp: new Date(Date.now() - 3600000 * 3 + 300000).toISOString(), note: 'Passageiro embarcou' },
      { status: 'corrida_concluida', timestamp: new Date(Date.now() - 3600000 * 3 + 900000).toISOString(), note: 'Chegada ao destino confirmada' },
    ],
  },
];

export const INITIAL_RECHARGES: CreditRecharge[] = [];
export const INITIAL_WITHDRAWALS: Withdrawal[] = [];
export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    timestamp: new Date().toISOString(),
    category: 'sistema',
    actorId: 'admin',
    actorName: 'Central Nexo Viagens',
    actorRole: 'admin',
    actionType: 'INICIALIZACAO_SISTEMA',
    description: 'Sistema Nexo Viagens inicializado com suporte a Supabase Realtime, Praças Dinâmicas e Gestão de Mototaxistas.',
  },
];
